// Sidebar for the "Engine Reference" docs instance (digital archaeology of the
// original engine). Auto-generated from the reference/ directory tree.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  referenceSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
