// Sidebar is auto-generated from the docs/ directory tree.
// Add/rename folders under docs/ and they appear here automatically.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
